@startuml
object "actAdministrator" as A1
object "outactAdministrator" as A2
object "inactAdministrator" as A3

A1 "1 rnActor" -- "1 rnInterfaceOUT" A2
A1 "1 rnActor" -- "1 rnInterfaceOUT" A3

A1 : init() = ptBoolean

A2 : sfCreateUserDirectory(ActUser: dtUser) = ptBoolean
A2 : sfDeleteUserDirectory(ActUser: dtUser) = ptBoolean
A2 : login(ActUser: dtUser, ActPwd: dtPwd) = ptBoolean
A2 : logout() = ptBoolean

A3 : ieMessage(Message: ptString) = ptBoolean
@enduml
